services:
    symfony.application:
      class: Symfony\Component\Console\Application
      arguments:
        - 'Dropcat'
        - '0.2.0'
    symfony.console_output:
      class: Symfony\Component\Console\Output\ConsoleOutput
    dropcat.configuration:
      class: Dropcat\Services\Configuration
    dropcat.command.tar:
        class: Dropcat\Command\TarCommand
        arguments: ['@dropcat.configuration']
        tags:
          - {name: console.command}
    dropcat.command.backup:
      class: Dropcat\Command\BackupCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.config-import:
      class: Dropcat\Command\ConfigImportCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.db-import:
      class: Dropcat\Command\DbImportCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.move:
      class: Dropcat\Command\MoveCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.symlink:
      class: Dropcat\Command\SymlinkCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.upload:
      class: Dropcat\Command\UploadCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.prepare:
      class: Dropcat\Command\PrepareCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.self-update:
      class: Dropcat\Command\SelfUpdaterCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.self-rollback:
      class: Dropcat\Command\SelfRollbackCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.init:
      class: Dropcat\Command\InitCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.about:
      class: Dropcat\Command\AboutCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.site-install:
      class: Dropcat\Command\SiteInstallCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.reset-login:
      class: Dropcat\Command\ResetLoginCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.jenkins-build:
      class: Dropcat\Command\JenkinsBuildCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.entity-update:
      class: Dropcat\Command\EntityUpdateCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.cache-recreate:
      class: Dropcat\Command\CacheRecreateCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.cache-clear:
      class: Dropcat\Command\CacheClearCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.update-database:
      class: Dropcat\Command\UpdateDatabaseCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
 #   dropcat.command.check-connection:
 #     class: Dropcat\Command\CheckConnectionCommand
 #     arguments: ['@dropcat.configuration']
 #     tags:
 #       - {name: console.command}
    dropcat.command.locale-update:
      class: Dropcat\Command\LocaleUpdateCommand
      arguments: ['@dropcat.configuration']
      tags:
        - {name: console.command}
