version: "3.7"
services:
  jenkins:
    container_name: jenkins
    build:
      context: services/jenkins/
    ports:
      - 8080:8080
      - 50000:50000
      - 22:22
    volumes:
      - jenkins-home:/var/jenkins_home
      - jenkins-backup:/backup
      - type: bind
        source: ./keys/id_rsa
        target: /var/id_rsa

  web:
    ports:
      - 8081:80
    container_name: web
    build:
      context: services/apache/
    volumes:
      - $PWD/apache:/var/www/html

volumes:
  jenkins-home:
    driver: local
  jenkins-backup:
    driver: local
